name: F1 Data Pipeline

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:      # Allows you to click a button to run it manually

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ELT Script
        env:
          # This maps your GitHub Secret to an environment variable
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python main.py