name: F1 Data Pipeline

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:      

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ELT Script (Extract & Load)
        working-directory: ./src
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python extract.py

      - name: Run dbt (Transform & Test)
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }} 
        run: |
          echo "$GCP_SA_KEY" > gcp_credentials.json
          
          # Move into the dbt directory and run
          cd dbt_f1
          dbt run --profiles-dir .
          dbt test --profiles-dir .